# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b816900f074324bc56d7d645e2063d50771fa32a2b4df9aa34c5e4a653ef5860372d8872eb3252bfce7f9f83bfb3e1988398baacc1119c65e7c5f59727d10442

test:
  secret_key_base: cc061e33c3fe607c51cf0ee2775248ed575add24438e1e387afd581e75a830f7ef11ee986e94778317a5a0d616e4abcabe304e90ba00d0100842d4eed235de64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
